name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: GitHub Container Registry (GHCR) Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: Mark-van-B #GitHub username goes here
        password: ${{ secrets.SECRET_KEY_IT_LANDSCAPE }} # See guide on making this key on GitHub. Too many steps to write in here...
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/mark-van-b/getting-started-app:$(date +%s) ##This adds the date to the logs.
                                                #  Name in lowercase/Replace the above with the name of your own app

    - name: Push the Docker image
      run: docker push ghcr.io/mark-van-b/getting-started-app:${{ github.sha }} #This basically adds a unique value to every push, for logging purposes.
